name: test-pr

on: 
  push:
    branches: [ main ]
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ '1.15', '1.16' ]
    name: Go ${{ matrix.version }}
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.version }}
    - if: ${{ github.event_name == 'pull_request_target' }}
      env:
        GITHUB_REF: ${{ format('refs/pull/{0}/merge', github.event.number) }}
    - uses: actions/checkout@v2
      with:
        ref: "$GITHUB_REF"
    - run: ./scripts/run-tests.sh -race -failOnPending -skipPackage=contract_tests,system_tests
  automerge:
    needs: test
    name: Merge Dependabot Pull Pequest
    runs-on: ubuntu-latest
    if: ${{ success() && github.actor == 'dependabot[bot]' }}
    steps:
      - name: Merge
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              merge_method: 'squash'
            })
