name: test-pr

on: 
  pull_request_target:

jobs:
  test:
	@@ -15,23 +15,5 @@ jobs:
      with:
        go-version: ${{ matrix.version }}
    - uses: actions/checkout@v2
      with:
        ref: $GITHUB_HEAD_REF
    - run: make test
  automerge:
    needs: test
    name: Merge Dependabot Pull Pequest
    runs-on: ubuntu-latest
    if: ${{ success() && github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]' }}
    steps:
      - name: Merge
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              merge_method: 'squash'
            })
